main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.21.1"
author: Corn
description: Jail Plugin
commands:
  jail:
    description: Manage jails and punishments
    usage: /jail <setup|player> [time]
  jailstick:
    description: Gives player stick to send people to jail, make sure they are guilty before you send them or else...
    usage: /jailstick <player>

