name: JailPlugin
main: com.corn.plugin.JailPlugin
version: 1.0
api-version: "1.21.1"
author: Corn
description: Provides jail commands and a jail stick to punish players.

commands:
  jailc:
    description: Jail system commands
    usage: /jailc <setup|player> [seconds] | stick
    aliases: [jail]

permissions:
  # Allows use of any /jailc command
  jailc.use:
    description: Allows using /jailc
    default: op
  jailc.setup:
    description: Allows the setup sub-command
    default: op
  jailc.jail:
    description: Allows jailing players
    default: op
  jailc.stick:
    description: Allows giving yourself the jail stick
    default: op
