name: JailPlugin
main: com.corn.plugin.JailPlugin
version: 1.0
api-version: "1.21.1"
author: Corn
description: Provides jail commands and a jail stick to punish players.

commands:
  jailc:
    description: Jail system commands
    usage: /jailc <setup|player> [seconds] | stick
    aliases: [jail]
