main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.21.1"
author: Corn
description: Jail Plugin
commands:
  jail:
    description: Jail command with subcommands
    usage: /jail <setup|playername>

